#
# Travis-CI configuration for dt-contribs.
#
sudo: false
language: node_js
node_js:
    - "0.10"

# Install TypeScript compiler to compile most definitions and test files.
# Install Bower which is used to retrieve client-side dependencies.
before_script: npm install -g typescript bower
script: npm test # Invoke dt-contribs test runner.
