#
# Travis-CI configuration for dt-contribs.
#

sudo: false
language: node_js
node_js:
    - "0.10"

# Install TypeScript compiler to compile definitions and test files.
before_script: npm install -g typescript 
script: npm test # Invoke dt-contribs test runner.
