#
# Travis-CI configuration for dt-contribs.
#

sudo: false
language: node_js
node_js:
    - "0.10"

# Install TypeScript compiler to compile most definitions and test files.
# Install Bower which is used to retrieve client-side dependencies.
# Install Gulp which is used to compile some definitions and tests.
before_script: npm install -g typescript bower gulp
script: npm test # Invoke dt-contribs test runner.
